chore(TDI-49637): Update json-smart for connectors-se
Talend/connectors-se pull request #1034
Opened 2023-04-06 18:22 UTC by dmytro-sylaiev

2023-04-14 15:24 UTC, ypiel-talend requested changes
One comment

2023-04-14 15:24 UTC, ypiel-talend commented on azure/pom.xml
> +        <version>2.4.9</version>
The cve is fixed in 2.4.10 as explained in veracode no ?
https://sca.analysiscenter.veracode.com/workspaces/X33hjMQ/issues/vulnerabilities/176795135

2023-04-18 14:14 UTC, dmytro-sylaiev commented on azure/pom.xml
> +        <version>2.4.9</version>
2.4.9 also fixed the direct CVE about parsing nested jsons: https://github.com/netplex/json-smart-v2/releases/tag/2.4.9
https://mvnrepository.com/artifact/net.minidev/json-smart

2.4.10 only fixes additional bug about it, but 2.4.9 is used in daikon and I updated to 2.4.9 to be aligned with daikon

2023-04-21 12:51 UTC, ypiel-talend approved these changes
LGTM

2023-04-27 08:41 UTC, merged