chore(TDI-49969): Move httpcommon to SE repo
Talend/connectors-se pull request #1083
Opened 2023-06-21 08:56 UTC by dmytro-sylaiev

2023-06-27 12:51 UTC, ypiel-talend commented
Add a README.md

2023-06-27 14:54 UTC, ypiel-talend requested changes
Good job, some comments

2023-06-27 14:54 UTC, ypiel-talend commented on http-common/src/main/java/org/talend/components/http/stream/json/dssl/JsonDsslConfiguration.java
> +    @Option
DSSL should not surface in -se I think.

2023-06-27 14:54 UTC, ypiel-talend commented on http-common/src/main/resources/org/talend/components/http/stream/xml/dssl/Messages.properties
> +XmlDsslConfiguration.dssl._displayName = XX XML Extract a sub-part of the response
We can remove all about XML It was a oversight to have left xml translations.

2023-06-27 16:32 UTC, dmytro-sylaiev commented on http-common/src/main/java/org/talend/components/http/stream/json/dssl/JsonDsslConfiguration.java
> +    @Option
it was decided to not split UI and throw an error only in runtime

2023-07-03 16:17 UTC, Gby56 commented
Not sure why there is a private key in here ? It triggered an alert on our end

2023-07-04 08:39 UTC, dmytro-sylaiev commented on http-common/src/main/java/org/talend/components/http/stream/json/dssl/JsonDsslConfiguration.java
> +    @Option
No affect to UI, moved to EE since stream-json is used in runtime for SE now

2023-07-04 12:36 UTC, ozhelezniak-talend reviewed
Looks ok, I didn't review the business logic of commons-httpclient
Left a few small comments

2023-07-04 12:36 UTC, ozhelezniak-talend commented on http-common/README.adoc
> +Please note that DSSL features not supported when your component extends http-common in connectors-se.
We mention here dssl, is it expected?

2023-07-04 12:36 UTC, ozhelezniak-talend commented on http-common/README.adoc
> +generatd file `TALEDN-INF/scanning.properties`.
"generated" - typo

2023-07-04 12:36 UTC, ozhelezniak-talend commented on http-common/pom.xml
> +        <!-- Some component-runtime maven plugin verication disabled since no connector in this module. -->
"verification" typo?

2023-07-04 12:36 UTC, ozhelezniak-talend commented on http-common/src/main/java/org/talend/components/http/service/AttachmentService.java
> +                is = new ByteArrayInputStream(new byte[] {});
why? it should be "new byte[0]"

2023-07-04 12:36 UTC, ozhelezniak-talend commented on http-common/src/main/java/org/talend/components/http/service/provider/DictionaryProvider.java
> +                        throw new UnsupportedOperationException("DSSL not supported in SE code.");
"DSSL is not supported in SE code"

2023-07-04 12:37 UTC, dmytro-sylaiev commented on http-common/README.adoc
> +Please note that DSSL features not supported when your component extends http-common in connectors-se.
yes, it is readme to warn a user that some parts present in the API not working :)

2023-07-04 13:17 UTC, dmytro-sylaiev commented on common-httpclient/pom.xml
> +        <relativePath>../pom.xml</relativePath>
We have had it here previously: https://github.com/Talend/connectors-ee/blob/master/common/http-client/pom.xml#L9

Removed.

2023-07-04 13:18 UTC, dmytro-sylaiev commented on common-httpclient/pom.xml
> +        <jetty.version>11.0.11</jetty.version>
I don't think we need to change it in scope of code moving from EE to SE, too risky

2023-07-04 13:18 UTC, dmytro-sylaiev commented on http-common/README.adoc
> +generatd file `TALEDN-INF/scanning.properties`.
fixed, thank you

2023-07-04 13:19 UTC, dmytro-sylaiev commented on http-common/pom.xml
> +        <!-- Some component-runtime maven plugin verication disabled since no connector in this module. -->
Fixed, thank you

2023-07-04 13:41 UTC, dmytro-sylaiev commented on http-common/src/main/java/org/talend/components/http/service/provider/DictionaryProvider.java
> +                        throw new UnsupportedOperationException("DSSL not supported in SE code.");
fixed

2023-07-04 13:41 UTC, dmytro-sylaiev commented on http-common/src/main/java/org/talend/components/http/service/AttachmentService.java
> +                is = new ByteArrayInputStream(new byte[] {});
fixed

2023-07-04 13:48 UTC, ozhelezniak-talend approved these changes
looks lgtm

2023-07-07 11:42 UTC, ozhelezniak-talend approved these changes
lgtm

2023-07-13 08:43 UTC, merged