Clesaec/tdi 44195 sonar analyse
Talend/connectors-se pull request #452
Opened 2020-07-30 06:42 UTC by clesaec

2020-07-30 08:15 UTC, rlecomte-talend submitted a review, later dismissed
LGTM

2020-11-02 15:53 UTC, undx reviewed
We have a two distinct purposes/goals in that PR, please split it in two different PRs.
That's more pertinent and in the case we've to revert...

2020-11-02 15:53 UTC, undx requested changes
See previous comment.

2020-11-03 12:29 UTC, undx approved these changes
LGTM 
Just change label as commented.

2020-11-03 12:29 UTC, undx commented on Jenkinsfile
> +        booleanParam(name: 'FORCE_SONAR', defaultValue: false, description: 'Turn to true to force sonar analysis')
Rather say: _Force Sonar analysis_

2020-11-03 13:03 UTC, undx approved these changes
LGTM

2020-11-03 13:05 UTC, merged