feat(TDI-45261) : Prevent REST connector to access internal api of a cloud engine
Talend/connectors-se pull request #497
Opened 2020-11-25 16:47 UTC by ypiel-talend

https://jira.talendforge.org/browse/TDI-45261

2020-11-26 09:25 UTC, coheigea requested changes

2020-11-26 09:25 UTC, coheigea commented on common/src/main/java/org/talend/components/common/service/http/ValidateSites.java
> +    private final static List<String> ADDITIONAL_LOCAL_HOSTS = Arrays.asList(new String[] { "224.0.0" // local multicast : from
We should change 224.0.0 -> 224.0.0. - as otherwise it could match xxx.224.0.0 ?

2020-11-26 09:25 UTC, coheigea commented on common/src/main/java/org/talend/components/common/service/http/ValidateSites.java
> +     * @param enable_multicat_access
enable_multicat_access -> enable_multicast_access

2020-11-26 09:25 UTC, coheigea commented on common/src/main/java/org/talend/components/common/service/http/ValidateSites.java
> +                    && !ADDITIONAL_LOCAL_HOSTS.stream().filter(h -> host.contains(h)).findFirst().isPresent();
Should we use isLoopbackAddress() here instead?

2020-11-26 10:16 UTC, rlecomte-talend commented on common/src/main/java/org/talend/components/common/service/http/ValidateSites.java
> +    private final static List<String> ADDITIONAL_LOCAL_HOSTS = Arrays.asList(new String[] { "224.0.0" // local multicast : from
Done

2020-11-27 09:19 UTC, rlecomte-talend commented on common/src/main/java/org/talend/components/common/service/http/ValidateSites.java
> +     * @param enable_multicat_access
Done

2020-12-01 16:57 UTC, coheigea approved these changes

2020-12-02 19:04 UTC, dmytro-sylaiev commented on common/src/main/java/org/talend/components/common/service/http/ValidateSites.java
> +            System.getenv().getOrDefault("CONNECTORS_ENABLE_LOCAL_NETWORK_ACCESS", "true")));
if not specified, access to local API is allowed. Is it intended? So where does it specified then?

2020-12-02 19:06 UTC, dmytro-sylaiev approved these changes
LGTM if access is ON by default

2020-12-03 11:56 UTC, coheigea commented
Looks like there is a conflict that needs to be updated.

2020-12-07 07:58 UTC, rlecomte-talend commented on common/src/main/java/org/talend/components/common/service/http/ValidateSites.java
> +            System.getenv().getOrDefault("CONNECTORS_ENABLE_LOCAL_NETWORK_ACCESS", "true")));
Yes, that's the default behavior.

2020-12-07 09:16 UTC, coheigea approved these changes

2020-12-07 14:11 UTC, dmytro-sylaiev approved these changes
LGTM

2020-12-21 09:42 UTC, merged