feat(TDI-44723): add truncate option
Talend/connectors-se pull request #503
Opened 2020-12-01 10:52 UTC by OleksiiNimych

https://jira.talendforge.org/browse/TDI-44723
Add truncate option to the bigquery connector

2020-12-01 12:45 UTC, rlecomte-talend submitted a review, later dismissed
LGTM

2020-12-01 14:57 UTC, ypiel-talend requested changes
Some remarks

2020-12-01 14:57 UTC, ypiel-talend commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +            log.warn("BigQuery was unable to load into the table due to an error:" + job.getStatus().getError());
Work item to define a clear rule about what should append on such error ?
- stop pipeline ?
- Define a reject flow ?
- just log as here ?

2020-12-01 14:57 UTC, ypiel-talend commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
>      private TableReference createTableReference() {
Remove if not used.

2020-12-01 14:57 UTC, ypiel-talend commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutputConfig.java
> +        TRUNCATE,
Should be possible to have CREATE_IF_NOT_EXIST + TRUNCATE at the same time.
For instance bigquery config in studio:
![image](https://user-images.githubusercontent.com/29707101/100756541-93827c00-33ed-11eb-8425-c7683e4c4aaa.png)

2020-12-01 14:57 UTC, ypiel-talend commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +            log.warn("BigQuery was unable to load into the table due to an error:" + job.getStatus().getError());
warn message should be i18n

2020-12-01 16:30 UTC, OleksiiNimych commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +            this.recordWriter.end();
.close() call in the .end()
https://github.com/Talend/connectors-se/blob/master/common-stream-io/stream-api/src/main/java/org/talend/components/common/stream/api/output/RecordWriter.java#L28-L31

2020-12-01 17:14 UTC, OleksiiNimych commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +            log.error(exIO.getMessage());
done

2020-12-01 17:14 UTC, OleksiiNimych commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +                log.warn(e.getMessage());
done

2020-12-01 17:15 UTC, OleksiiNimych commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +        Schema schema = table.getDefinition().getSchema();
Updated to use tableSchema

2020-12-01 17:16 UTC, OleksiiNimych commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +        Job job = bigQuery.create(jobInfo);
Added code that recall the method to load the data

2020-12-01 17:16 UTC, OleksiiNimych commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
>      private TableReference createTableReference() {
Removed

2020-12-01 17:16 UTC, OleksiiNimych commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +            log.warn("BigQuery was unable to load into the table due to an error:" + job.getStatus().getError());
Added i18n

2020-12-01 17:29 UTC, ypiel-talend approved these changes
LGTM

2020-12-09 10:21 UTC, ypiel-talend requested changes
Need a change

2020-12-09 10:21 UTC, ypiel-talend commented on bigquery/src/main/java/org/talend/components/bigquery/output/BigQueryOutput.java
> +        bigQuery = service.createClient(connection);
What was identify in previous code review is :
"Everything that can have side-effect on your treatment (ie : is part of your treatment) should not be in setup (@PostConstruct) nor teardown (@PreDestroy)."
Here it manages the truncate of the table, it can have side effect on the treatment so should not be in @PostConstruct.

You can move it in @BeforeGroup.

But it will be called more often and so 'bigQuery.getJob(jobId)' that can take some times !
To improve performance, we can rely on a service method with a local cache.
So, could you try to change 'bigQuery.getJob(jobId)' by something like 'service.isJobDone(jobId)'.
Use a LocalCache Service (built-in service of TCK) to check if there is a value for jobId key, 
if not, call  'bigQuery.getJob(jobId)'
and if not null store a boolean in the cache, so next call you will see in the cache thatthe job was done, and you will not have to call bigquery.

2020-12-11 09:44 UTC, ypiel-talend approved these changes
LGTM

2020-12-16 14:28 UTC, merged