Clesaec/tdi 45370 common test
Talend/connectors-se pull request #535
Opened 2021-01-08 15:44 UTC by clesaec

https://jira.talendforge.org/browse/TDI-45370

Add a common module that help to design unit test.
This for Record & Assertions generator.

2021-01-14 13:14 UTC, chmyga requested changes
If we add those classes we need to check all possible data types in them. Maybe it would be easier to drop them and check everything manually?

2021-01-14 13:14 UTC, chmyga commented on common-stream-io/stream-json/src/test/java/org/talend/components/common/stream/output/json/JsonExpected.java
> +        }
Check of some possible types is missing

2021-01-14 13:14 UTC, chmyga commented on common-stream-io/stream-avro/src/test/java/org/talend/components/common/stream/output/avro/AvroExpected.java
> +        }
Check of some possible types are missing

2021-01-14 14:23 UTC, clesaec commented on common-stream-io/stream-json/src/test/java/org/talend/components/common/stream/output/json/JsonExpected.java
> +        }
tests added

2021-01-14 14:23 UTC, clesaec commented on common-stream-io/stream-avro/src/test/java/org/talend/components/common/stream/output/avro/AvroExpected.java
> +        }
tests added

2021-01-19 13:32 UTC, chmyga approved these changes
LGTM

2021-01-19 13:37 UTC, merged