fix(TDI-46715): Check Jdbc input query is one single query
Talend/connectors-se pull request #681
Opened 2021-09-13 09:17 UTC by tlnd-afournier

As explained in https://jira.talendforge.org/browse/TDI-46715, 
When a user create a dataset using jdbc connection and an input query,
he can chain queries in a one-liner using the `;` separator.
Doing so, the read-only check is bypassed and a user can performed non readonly operations.

This fix is a quick/dirty fix, there are certainly more uncovered use cases and we can't find them all using regexes.
However the new SQL compiler of Processing Runtime will be using a SQL parser (Apache Calcite), therefore a better solution might be found then.

2022-01-05 14:34 UTC, Gby56 approved these changes
LGTM

2022-01-05 23:57 UTC, ypiel-talend requested changes
There are some comments in the Jira.

2022-01-05 23:57 UTC, ypiel-talend commented on jdbc/src/main/java/org/talend/components/jdbc/input/AbstractInputEmitter.java
> +        if (jdbcDriversService.isNotReadOnlySQLQuery(query) || query.contains(";")) {
Too restrictive since the following acceptable query:
select * from a_field='some;content'
will be refused.

2022-01-06 08:34 UTC, Gby56 commented
Apache Calcite will likely be required to properly interpret the input and detect 1 or more queries then

2022-05-10 07:11 UTC, closed without merging