fix(TDI-46843): Change the error message for parquet azureblob ad auth
Talend/connectors-se pull request #710
Opened 2021-10-21 13:36 UTC by dmytro-sylaiev

2021-10-22 09:32 UTC, clesaec submitted a review, later dismissed
:+1:

2021-11-02 07:12 UTC, clesaec requested changes
Just one remark

2021-11-02 07:12 UTC, clesaec commented on azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/BlobFileReader.java
> +                throw new ComponentException(messageService.containerNotExist());
Add the name of container that is not exists in message : 
`messageService.containerNotExist(config.getContainerName())`
With containerNotExist(String name) method in interface and a {0} symbol in Messages.properties file.

2021-11-02 09:06 UTC, dmytro-sylaiev commented on azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/BlobFileReader.java
> +                throw new ComponentException(messageService.containerNotExist());
it doesn't work for some reason

2021-11-02 09:07 UTC, dmytro-sylaiev commented on azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/BlobFileReader.java
> +                throw new ComponentException(messageService.containerNotExist());
the error message on the PD still contains "{0}" instead of a parameter

2021-11-02 10:12 UTC, clesaec commented on azure/azureblob/src/main/java/org/talend/components/azure/runtime/input/BlobFileReader.java
> +                throw new ComponentException(messageService.containerNotExist());
Strange, it works on other connector : [jdbc for example](https://github.com/Talend/connectors-se/blob/master/jdbc/src/main/resources/org/talend/components/jdbc/service/Messages.properties#L4)

2021-11-02 10:52 UTC, clesaec submitted a review, later dismissed
:+1:

2021-11-08 06:47 UTC, clesaec approved these changes
:+1:

2021-11-17 09:13 UTC, merged