Dsylaiev/tdi 46813 rewrite adls using new sdk
Talend/connectors-se pull request #728
Opened 2021-11-26 21:53 UTC by dmytro-sylaiev

https://jira.talendforge.org/browse/TDI-46806 (and subtasks)

2021-11-29 08:00 UTC, clesaec requested changes
Good job, code is simplify & more reliable 
Just one remark about removable class.

2021-11-29 13:28 UTC, dmytro-sylaiev commented on azure/azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/AdlsDatastoreRuntimeInfo.java
>      }
Thank you, good catch. Removed both Datastore and Dataset runtime infos, they are not needed anymore

2021-11-29 14:52 UTC, clesaec approved these changes
:+1:

2021-12-06 16:49 UTC, clesaec reviewed
Just a "online" review

2021-12-06 16:49 UTC, clesaec commented on azure/azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/AdlsGen2Service.java
> +        PipedOutputStream pipedOutputStream = new PipedOutputStream();
Here, it would be better to integrate a InputStream consumer as to return InputStream :
```java
public void getBlobInputstream(AdlsGen2DataSet dataSet,
                                                  BlobInformations blob,
                                                  Consumer<InputStream> client) throws IOException {
```
(or a specific consumer to catch potential exception)

2021-12-06 16:49 UTC, clesaec commented on azure/azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/AdlsGen2Service.java
> +        return pipedInputStream;
```java
try (PipedInputStream pipedInputStream = new PipedInputStream();
        PipedOutputStream pipedOutputStream = new PipedOutputStream(pipedInputStream)) {
         Thread writer = new Thread(() -> client.consume(pipedInputStream));
         writer.start();
         blobFileClient.read(pipedOutputStream);
         pipedOutputStream.flush();
         writer.join();
    }
}
```
should almost work (should work with exceptions catching and specific interface for client instead of basic java.util.Consumer)

2021-12-31 08:45 UTC, pyzhou-talend approved these changes

2021-12-31 08:59 UTC, merged