feat(TDI-47199): recreated changes after research issue.
Talend/connectors-se pull request #737
Opened 2021-12-08 17:36 UTC by dmytrogrygorenko

https://jira.talendforge.org/browse/TDI-47199
Migrating existing Couchbase component to new SDK v.3 to support Couchbase Server v 7.0 and higher.

2021-12-22 16:13 UTC, dmytro-sylaiev requested changes
Please fix the bug with migration and check if the injection is not a problem for couchbase.

2021-12-22 16:13 UTC, dmytro-sylaiev commented on couchbase/src/main/java/org/talend/components/couchbase/service/CouchbaseService.java
> +        String[] addresses = nodes.replace(" ", "").split(",");
Is it an expected change?

2021-12-23 09:14 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/service/CouchbaseService.java
> +        String[] addresses = nodes.replace(" ", "").split(",");
Yes. replaceAll() expects regular expression as an argument; if it's not the case, behavior is similar to the one defined in replace() method, but overall performance is better.

2021-12-23 09:20 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/source/parsers/ParserFactory.java
> +            throw new ComponentException("Parser factory. Unknown document type: " + documentType);
Check for happens in :

2021-12-23 11:50 UTC, dmytro-sylaiev commented on couchbase/src/main/java/org/talend/components/couchbase/source/parsers/ParserFactory.java
> +            throw new ComponentException("Parser factory. Unknown document type: " + documentType);
Ok, let it be "Not expected document type" and put some comment here so another developer which got this exception could easy understand why it is not expected

2021-12-23 14:56 UTC, clesaec commented on couchbase/src/main/java/org/talend/components/couchbase/source/CouchbaseInput.java
> +                throw new ComponentException(e.toString());
even more, it's only mandatory in ComponentException (msg goes to the UI) ;-).

2021-12-23 15:13 UTC, clesaec requested changes
Small change to do about transient fields.

2021-12-23 15:13 UTC, clesaec commented on couchbase/src/main/java/org/talend/components/couchbase/output/CouchbaseOutput.java
> +    private Collection collection;
Put  fieds Cluster & Collection as transient (not serializable)

2021-12-23 15:13 UTC, clesaec commented on couchbase/src/main/java/org/talend/components/couchbase/source/CouchbaseInput.java
> +    private Collection collection;
Same, put fields iterator & collection as transient.

2021-12-24 08:52 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/datastore/CouchbaseDataStoreMigrationHandler.java
> +        if (incomingVersion < 3 && "true".equals(incomingData.get("useConnectionParameters"))) {
Fixed - second clause was removed.

2021-12-24 08:52 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/datastore/CouchbaseDataStoreMigrationHandler.java
> +                if (entry.getValue().equals("MAX_REQUEST_LIFETIME")) {
Fixed.

2021-12-24 08:52 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/source/parsers/ParserFactory.java
> +            throw new ComponentException("Parser factory. Unknown document type: " + documentType);
Done. Comment added, exception message modified to be clearer.

2021-12-24 08:52 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/source/CouchbaseInput.java
> +                throw new ComponentException(e.toString());
Fixed.

2021-12-24 08:54 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/output/CouchbaseOutput.java
> +    private Collection collection;
Actually, adaptations for PD will be done in another feature (https://jira.talendforge.org/browse/TDI-47200), but we can do it here. Added "transient" modifier.

2021-12-24 08:54 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/source/CouchbaseInput.java
> +    private Collection collection;
Done.

2021-12-27 06:49 UTC, clesaec submitted a review, later dismissed
LGTM

2022-01-11 07:31 UTC, dmytrogrygorenko commented on couchbase/src/main/java/org/talend/components/couchbase/source/CouchbaseInput.java
> +                statementBuilder.append("SELECT meta().id as `_meta_id_`, * FROM `").append(bucket.name()).append("`");
Tried to simulate, but could not perform an injection. The idea was to insert some sample injection command to the field where bucket name should be defined. But since we currently do not have tCouchbaseConnection component available, every Couchbase component will create its own connection, and this will raise an exception since this "bucket with injection" could not be found for the connection.

2022-01-11 15:31 UTC, dmytro-sylaiev approved these changes
LGTM

2022-01-14 15:35 UTC, dmytro-sylaiev approved these changes
👍

2022-02-09 12:46 UTC, clesaec approved these changes
:+1:

2022-02-09 12:50 UTC, merged