chore(TDI-47412): Reflect cloud-compo build/release improvements
Talend/connectors-se pull request #781
Opened 2022-01-21 16:55 UTC by ypiel-talend

https://jira.talendforge.org/browse/TDI-47412

2022-03-03 17:19 UTC, davroussel requested changes
See my comments

2022-03-03 17:35 UTC, davroussel submitted a review, later dismissed

2022-03-04 14:36 UTC, quilicicf commented on .jenkins/build.sh
> +  branch="${1?Missing branch name}"; shift
This parameter is not documented.

2022-03-04 14:51 UTC, quilicicf commented on jdbc/pom.xml
> +                    <url>https://mvnrepository.com/artifact/</url>
Can we move this change in a future commit and explain it? 
There must be a reason it starts failing locally with the previous version but not on CI.

2022-03-04 14:54 UTC, quilicicf submitted a review, later dismissed

2022-03-04 14:57 UTC, quilicicf approved these changes

2022-03-04 14:59 UTC, merged