(APPINT-34262) solve the rs-api version conflict issue
Talend/connectors-se pull request #795
Opened 2022-02-15 06:55 UTC by xldai

2022-02-15 07:14 UTC, pyzhou-talend approved these changes
LGTM

2022-02-15 07:21 UTC, pyzhou-talend requested changes
As @pierre mentioned, this dependency has CVE issue.

2022-02-15 08:58 UTC, pyzhou-talend approved these changes

2022-02-22 03:00 UTC, xldai commented
close this PR, this will be fixed in scope of TDI-46768.

2022-02-22 03:00 UTC, closed without merging