Chore(TDI-48532) Automated malformed encoding fix
Talend/connectors-se pull request #927
Opened 2022-09-27 12:20 UTC by fdesiles

https://jira.talendforge.org/browse/TDI-48532

Updating post login actions to always check for m2 corruption and clean the possible associated items.

2022-09-27 13:09 UTC, acatoire approved these changes
LGTM

2022-11-21 16:45 UTC, fdesiles commented
> LGTM

Updated PR to avoid grep on M2 when no problem exists (adds many minutes to builds).
Now the clean will be done when a Malformed Encoding is detected in the logs. So further builds won't be blocked.

2022-11-22 09:01 UTC, acatoire requested changes
Why are you not using the function like in  cloud-components PR?
https://github.com/Talend/cloud-components/blob/e855d4f543feda55ee075c7681fa85bb376130dc/Jenkinsfile#L462-L463

2022-11-22 13:26 UTC, fdesiles commented
> Why are you not using the function like in cloud-components PR? https://github.com/Talend/cloud-components/blob/e855d4f543feda55ee075c7681fa85bb376130dc/Jenkinsfile#L462-L463

I do, please recheck :)

2022-11-22 13:36 UTC, acatoire approved these changes
LGTM

2022-11-23 14:59 UTC, fdesiles commented on Jenkinsfile
> +        echo 'Malformed encoding detected: Cleaning M2 corruptions'
```suggestion
    //Clean M2 corruptions - TDI-48532
    echo 'Checking for Malformed encoding error'
    if (logContent.contains("Malformed \\uxxxx encoding")) {
        echo 'Malformed encoding detected: Cleaning M2 corruptions'
```

2022-11-23 15:53 UTC, acatoire approved these changes
LGTM

2022-11-23 17:15 UTC, merged