chore(TDI-48973): Fix Sonar NoClassDefFoundError
Talend/connectors-se pull request #973
Opened 2022-12-01 15:52 UTC by fdesiles

https://jira.talendforge.org/browse/TDI-48973

Following SFT bump of Sonar in 9.6, builds are failing with:
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/collect/LinkedListMultimap$1KeySetImpl
 
This is linked to a bug on 9.6 using Sonar cache.

It is fixed in 9.7.1, however there is another blocker for SFT to stay on version 9.6 for the time being.

2022-12-01 16:44 UTC, ypiel-talend submitted a review, later dismissed
LGTM

2022-12-01 16:47 UTC, acatoire requested changes

2022-12-01 16:47 UTC, acatoire commented on .jenkins/build.sh
> +    # TODO Disabling Sonar cache due to "ClassNotFoundException: com.google.common.collect.LinkedListMultimap" issue
```suggestion
    # TODO: TDI-48980 - Disabling Sonar cache due to "ClassNotFoundException: com.google.common.collect.LinkedListMultimap" issue
```
Could you add the ticket id on same line that the todo for future scan

2022-12-02 08:31 UTC, acatoire approved these changes
LGTM

2022-12-02 08:51 UTC, merged